### ISSUE TITLE
Photo Needed: Teal PHP7

### ISSUE THREAD

**Issue by philipsharp** [philipsharp/afieldguidetoelephpants#11]

**Comment by MarkBaker** [comment]
cf [PR #23](https://github.com/philipsharp/afieldguidetoelephpants/pull/23)

**Comment by jrfnl** [comment]
You're also welcome to use this herd one - http://snag.gy/MAltS.jpg -, though @dragonbe probably has a better one:

![teal herd](http://snag.gy/MAltS.jpg)

**Comment by DragonBe** [comment]
Well, I've got 110 #elephpant pictures all CC by-nc-nd, find them on Flickr.

https://www.flickr.com/search/?user_id=99777199%40N00&sort=date-taken-desc&text=elephpant&view_all=1
