### ISSUE TITLE
Photo Needed: HHVM pHackyderm

### ISSUE THREAD

**Issue by philipsharp** [philipsharp/afieldguidetoelephpants#12]

**Comment by adduc** [comment]
Looks like @calevans had a photo: https://twitter.com/CalEvans/status/642469721208582144

**Comment by philipsharp** [comment]
I'm hoping to get a picture with just the elephpant. The front is also distinctive.

**Comment by jrfnl** [comment]
Maybe not the "cleanest" picture, but something like this: http://snag.gy/U8O9U.jpg ?

**Comment by cookieguru** [comment]
Another one from @adamculp:
https://www.flickr.com/photos/adamculp/24834461270/

**Comment by philipsharp** [comment]
Resolved with #30
