### ISSUE TITLE
Adds a picture of the first elephpant ever

### ISSUE THREAD

**Issue by dseguy** [philipsharp/afieldguidetoelephpants#13]
Here is a picture of L'aieul (the ancestor), the first elephpant ever. He still exists, though it is resting.

Also, the first large elephpant ever bears the name of 'papa' and acted as the father for the first 15000 elephants. Sadly, the mother is not to be found anymore. :(

http://bit.ly/1PmiN46
![548695738_866957a9de_o](https://cloud.githubusercontent.com/assets/170418/11060714/4aa91c3e-87a2-11e5-88c0-71def3c7298f.png)

**Comment by philipsharp** [comment]
@dseguy Was this the prototype or one of the first generation? I haven't seen any other elephpants with the blue lettering like this.

**Comment by dseguy** [comment]
This is the prototype of the first generation. The manufacturer didn't get the color of the letter well, but the rest was perfect.

**Comment by dseguy** [comment]
I still have it, I may get him out of his retirement home by christmas and make a more recent picture.

**Comment by dseguy** [comment]
Sorry, the old elephpant is still sleeping. It may take some more time to take a recent picture.

**Comment by philipsharp** [comment]
I'm going to leave this out for now. I'm trying to use pictures with just the elephpants in them.

**Comment by dseguy** [comment]
OK. I'll try to get a old picture without anyone on it.

**Comment by dseguy** [comment]
There, here is a recent picture of the oldest elephpant. 

![img_9105](https://cloud.githubusercontent.com/assets/170418/19696441/61222b14-9ae7-11e6-90f9-0d1363344333.jpg)

**Comment by philipsharp** [comment]
This picture has been added. Thanks!
