### ISSUE TITLE
Adds the special 20th Haphpy birthday 

### ISSUE THREAD

**Issue by Wilkins** [philipsharp/afieldguidetoelephpants#19]
One elephpant is missing, the HaPHPy elePHPant:
https://twitter.com/haphpy20/status/674935102779097088

It is a unique one offered for the 20th PHP birthday to the Kenya User Group for their contribution.

**Comment by philipsharp** [comment]
Do you know what the license is for the photo?

**Comment by Wilkins** [comment]
No I don't. And we won't get much more photos, because the elephpant seems lost/stolen.

**Comment by woecifaun** [comment]
@philipsharp @Wilkins You can use te picture. You do not nee to mention the author.

I can check for a larger file of this picture if you need.

**Comment by woecifaun** [comment]
Here is a the file in a larger size.

![haphpy-elephpant](https://cloud.githubusercontent.com/assets/5421942/13169748/072281b8-d6e8-11e5-9ef4-0b23b484a247.jpg)

Just let me know when you merge / deploy it. :-)
