### ISSUE TITLE
Adding the Blue Magento Elephpant

### ISSUE THREAD

**Issue by ins0** [philipsharp/afieldguidetoelephpants#24]
There is also a Blue Elephpant from Magento. Currently i don't know anything about this little guy. Also this fellow dude had a different shape then the usually elephpant, so idk if he can be count as an "Elephpant".

https://twitter.com/RaeKnowler/status/700303522915602432

**Comment by ToughSee** [comment]
This one is a counterfeit one produced by some guys in Ukrain. They stopped producing anything a few months ago. Be careful if you find one, not sure they are safety tested.

**Comment by ins0** [comment]
I will close this as already mentioned that this is not a "original" one.

**Comment by philipsharp** [comment]
I've updated the CONTRIBUTING file to indicate that only "official" elephants will be included for now.
