### ISSUE TITLE
Maybe add information about the never released Apigility one ?

### ISSUE THREAD

**Issue by jrfnl** [philipsharp/afieldguidetoelephpants#27]
I seem to remember seeing a photo of a prototype on Twitter a few years back (or maybe it was just a drawing).

It was intended for one of the ZendCon conferences. Was a blue elephant with a rocket on its back if I remember correctly.

AFAIK it ended up never getting produced because it was deemed inappropriate as tensions around Israel were flaring up again around the time.

**Comment by jrfnl** [comment]
Oh, just thinking, @weierophinney might be able to point you a picture

**Comment by weierophinney** [comment]
Actually, @adamculp had the prototype, IIRC.

**Comment by adamculp** [comment]
Yes, still sitting on the shelf with the rest of the PHPamily. [http://geekyboy.com/images/apigility_proto.jpg](http://geekyboy.com/images/apigility_proto.jpg)

**Comment by ins0** [comment]
Haha how cool :) thanks @weierophinney @adamculp - didn't know this cutie exist :+1:

**Comment by adamculp** [comment]
The backstory: We were originally going to produce the Apigility elePHPant for ZendCon 2014. However, leading up to ZendCon there were many rocket attacks over Israel. Someone felt the elePHPant looked like it was launching a rocket, and it was decided that the possibility was too sensitive at the time. So we created the elePHPant with the Z-Ray goggles instead.

**Comment by adamculp** [comment]
Pull request added, for this and other images.

**Comment by jrfnl** [comment]
:+1:

**Comment by philipsharp** [comment]
Resolved with #30
