### ISSUE TITLE
Photo Needed: Pink

### ISSUE THREAD

**Issue by philipsharp** [philipsharp/afieldguidetoelephpants#4]

**Comment by rdohms** [comment]
Here you go https://www.flickr.com/photos/akrabat/6326066555/in/photolist-aD1Kc2-ni88rE-ak9mT1-azyd2Y-azydhd-oei683-iuRqcP-nWSMh4-asz4HK-asBHgd-6r9fK3-6r55tT-dogqkh-hJBWdc-6r9ffm-4EnaXY-gsJA9K-inEqEj-aTU66R-jxfJbF

I'm sure @akrabat will allow you to use it.

**Comment by akrabat** [comment]
Yes. Feel free to use it. I've updated the license on Flickr for that image, too.

**Comment by philipsharp** [comment]
Thanks guys!
