### ISSUE TITLE
Adding Images of the Large Elephpants

### ISSUE THREAD

**Issue by ins0** [philipsharp/afieldguidetoelephpants#42]
Should we include Images for the large Elephpants? 

```
| Small Elephpant Image | Small Elephpant Image |
-------------------------------------------------
| Big Elephpant Image   |  Big Elephpant Image  |
```

**Comment by smugphilip** [comment]
I know the designs are subtly different, but I don't think they're different enough to want to have them on every color. A side-by-side picture of the two sizes would probably be worth adding if we can get it for a color or two.

**Comment by philipsharp** [comment]
I know the designs are subtly different, but I don't think they're different enough to want to have them on every color. A side-by-side picture of the two sizes would probably be worth adding if we can get it for a color or two.
