### ISSUE TITLE
Regenerate site

### ISSUE THREAD

**Issue by ciaranmcnulty** [philipsharp/afieldguidetoelephpants#55]
Looks like a few PRs have been accepted without the page being regenerated - set up some sort of CI to do so on merge maybe?

**Comment by philipsharp** [comment]
I do merges and edits in batches, but I didn't have the time to rebuild last time. I'd like to do it automatically but a lot of PRs need a tweak or two. Rather than wait on the submitter to update them I usually fix the problems myself. I keep the build manual to avoid breaking the site.
