### ISSUE TITLE
Add Purple PHPConPoland elePHPant

### ISSUE THREAD

**Issue by cookieguru** [philipsharp/afieldguidetoelephpants#57]
@ojalehto Can you help with this one?

**Comment by ojalehto** [comment]
Sure. I'll add it soon even though it is kinda unofficial because it is not produced by the same company.

**Comment by cookieguru** [comment]
Ah, so that's why I hadn't heard of it before.  @philipsharp are we adding non-official elePHPants?

**Comment by ojalehto** [comment]
I created a PR for this. @philipsharp you can decide if you wan't to merge it or leave it out because it's non-official.

**Comment by philipsharp** [comment]
I haven't been including unofficial elephpants so far. Maybe the answer is to add a separate section (like the "Related Species"). I'll update this when I've decided.

**Comment by philipsharp** [comment]
For now I'm going to leave the unofficial ones out.
