### ISSUE TITLE
Add gray Roave elephpant

### ISSUE THREAD

**Issue by philipsharp** [philipsharp/afieldguidetoelephpants#62]
https://twitter.com/RoaveTeam/status/826942192015007744

**Comment by asgrim** [comment]
I'm running the @Roave elePHPant project, they're currently almost finished production, so should be with me in the next few months (sea-shipping is slow!). Please ping me if you need anything from me :)

**Comment by philipsharp** [comment]
Thanks @asgrim! The hardest part of adding any elephpant is getting clear, uncluttered, CC-licensed photos. If you have (or can get) any, please let me know.

**Comment by asgrim** [comment]
This photos are my own work, and happy to release them on CC-BY-SA license :) hopefully they're ok?

![2017-09-28 10 42 24](https://user-images.githubusercontent.com/496145/30957211-eb7de6e8-a439-11e7-8e19-e2ef0bc89e89.jpg)
![2017-09-28 10 42 37](https://user-images.githubusercontent.com/496145/30957210-eb775a80-a439-11e7-86c7-6afc8b4f08dc.jpg)

**Comment by philipsharp** [comment]
Great. Thank you!
