### ISSUE TITLE
Public API?

### ISSUE THREAD

**Issue by matthewtrask** [philipsharp/afieldguidetoelephpants#69]
Hey, Im working on a site to allow people across the world to trade elephpants and we would love to use the data you have if possible. Would you consider a public api? I have no problem building it if you are cool with it.

**Comment by philipsharp** [comment]
I hadn't thought about it before but I'm not opposed. Since the site is hosted statically there's a limit to what can be done easily. Is a full data set (like Colin added in #71) enough or will you need something more fine-grained?

**Comment by matthewtrask** [comment]
What Colin mentioned in #71 would be perfect. In fact, since the elephpant data isn't changing often, I wouldnt need to hit the API endpoint more then once every 6 months to a year at the most.

**Comment by cookieguru** [comment]
@matthewtrask, if @philipsharp was up to it, do you think you could build an API on your end and then a commit hook could be added on this repo to "push" changes as they occur?

**Comment by matthewtrask** [comment]
@cookieguru that sounds like a fantastic idea.

**Comment by philipsharp** [comment]
@matthewtrask You underestimate how much the data changes. It seems like there's a new elephpant every month!

I think we should build this into the site. I'm going to take a closer look at Colin's code and see if that will work for all of us.

**Comment by ramondelafuente** [comment]
I'm up for pitching in on this, we're also using the field guide as the definitive resource for https://elewant.com

**Comment by philipsharp** [comment]
This data is now available at: http://afieldguidetoelephpants.net/data/all.json
