### ISSUE TITLE
Relicense included source code

### ISSUE THREAD

**Issue by philipsharp** [philipsharp/afieldguidetoelephpants#80]
The Field Guide is published under the Creative Commons 
Attribution-NonCommercial-ShareAlike (BY-NC-SA) license.

When it was created there was nothing in the repository except the content. Now there is additional PHP code for extending Twig and rendering the JSON feed.

Creative Commons specifically recommends against using the BY-NC-SA license on software: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

I'm considering updating the license to leave the content as BY-NC-SA but relicense the source code under the MIT license.

**Comment by philipsharp** [comment]
@colinodell you're the only other source code contributor. Would you agree to this?

**Comment by colinodell** [comment]
Yeah, that sounds good to me!
