### ISSUE TITLE
Photo Needed: Laravel (Red)

### ISSUE THREAD

**Issue by philipsharp** [philipsharp/afieldguidetoelephpants#9]

**Comment by Wilkins** [comment]
I have one. What kind of photo do you need ? Which angle ? Which license ?

**Comment by philipsharp** [comment]
@Wilkins The site is licensed [CC-BY-SA](http://creativecommons.org/licenses/by-nc-sa/4.0/), and all photos that are used have compatible licenses. Currently all the photos are loaded from Flickr, where the license is shown on the photo page.
